
services:
  # Apache + PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=mvc_crud
      - DB_USERNAME=mvc_user
      - DB_PASSWORD=mvc_password

  # MySQL Service
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mvc_crud
      MYSQL_USER: mvc_user
      MYSQL_PASSWORD: mvc_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 300M
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: